[advisories]
ignore = [
    "RUSTSEC-2024-0388", # Just linked in test from risc0-zkvm for groth16
    "RUSTSEC-2024-0370", # Just linked in test from risc0-zkvm for bonsai-sdk
]
informational_warnings = ["unmaintained", "unsound"]

[output]
deny = ["warnings", "unsound", "yanked"]
quiet = false
